name: dimondvoice
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase: ^2.2.2
  animated_text_kit: ^4.2.2
  supabase_flutter: ^2.5.6
  custom_button_builder: ^0.0.4
  audioplayers: ^6.0.0
  http: ^1.2.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
 
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assests/fonts/Ubuntu-Regular.ttf
          weight: 300
        - asset: assests/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assests/fonts/Ubuntu-Bold.ttf        
          weight: 700

  assets:
    - assests\white_logo.png
    - assests\images\audio-book 1.png
    - assests\images\imam.png
    - assests\images\microphoneGuy.png
    - assests\images\podcaster 1.png
    - assests\images\translate 1.png
    - assests\images\financial.png
    - assests\images\svg\translate-svgrepo-com.svg
    - assests\images\svg\islam-muslim-svgrepo-com.svg
    - assests\images\svg\microphone-svgrepo-com.svg
    - assests\images\svg\interview-svgrepo-com.svg
    - assests\images\svg\audiobook-svgrepo-com (1).svg
    - assests\images\icons\Arrow - Right Circle.png
    - assests\images\icons\Arrow - Left Circle.png
    - assests\images\icons\Arrow - Down Square.png
    - assests\images\icons\Bookmark.png
    - assests\images\icons\Camera.png
    - assests\images\icons\Document-fill.png
    - assests\images\icons\Document.png
    - assests\images\icons\Download.png
    - assests\images\icons\Home.png
    - assests\images\icons\pause.png
    - assests\images\icons\Play.png
    - assests\images\icons\Play2.png
    - assests\images\icons\Profile.png
    - assests\images\icons\Search.png
    - assests\images\icons\Setting.png
    - assests\images\icons\star-filled.png
    - assests\images\icons\star-outlined.png
    - assests\images\icons\Time Square.png
    - assests\images\icons\Upload.png
    - assests\images\icons\Paper.png
    - assests\images\icons\Volume Up.png
    - assests\images\icons\Search-fill.png
    
supabase_flutter: ^2.0.0
