name: dimondvoice
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase: ^2.2.2
  animated_text_kit: ^4.2.2
  supabase_flutter: ^2.5.6
  custom_button_builder: ^0.0.4
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
 
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assests/fonts/Ubuntu-Regular.ttf
          weight: 300
        - asset: assests/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assests/fonts/Ubuntu-Bold.ttf        
          weight: 700

  assets:
    - assests\white_logo.png
    - assests\images\audio-book 1.png
    - assests\images\imam.png
    - assests\images\microphoneGuy.png
    - assests\images\podcaster 1.png
    - assests\images\translate 1.png
    - assests\images\financial.png
    - assests\images\svg\translate-svgrepo-com.svg
    - assests\images\svg\islam-muslim-svgrepo-com.svg
    - assests\images\svg\microphone-svgrepo-com.svg
    - assests\images\svg\interview-svgrepo-com.svg
    - assests\images\svg\audiobook-svgrepo-com (1).svg
    
supabase_flutter: ^2.0.0
